# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_job_submit_response_msg import V0040JobSubmitResponseMsg  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040JobSubmitResponseMsg(unittest.TestCase):
    """V0040JobSubmitResponseMsg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040JobSubmitResponseMsg
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_job_submit_response_msg.V0040JobSubmitResponseMsg()  # noqa: E501
        if include_optional :
            return V0040JobSubmitResponseMsg(
                job_id = 56, 
                step_id = '0', 
                error_code = 56, 
                error = '0', 
                job_submit_user_msg = '0'
            )
        else :
            return V0040JobSubmitResponseMsg(
        )

    def testV0040JobSubmitResponseMsg(self):
        """Test V0040JobSubmitResponseMsg"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
