# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_openapi_nodes_resp import V0040OpenapiNodesResp  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040OpenapiNodesResp(unittest.TestCase):
    """V0040OpenapiNodesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040OpenapiNodesResp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_openapi_nodes_resp.V0040OpenapiNodesResp()  # noqa: E501
        if include_optional :
            return V0040OpenapiNodesResp(
                nodes = [
                    openapi_client.models.v0/0/40_node.v0.0.40_node(
                        architecture = '0', 
                        burstbuffer_network_address = '0', 
                        boards = 56, 
                        boot_time = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cluster_name = '0', 
                        cores = 56, 
                        specialized_cores = 56, 
                        cpu_binding = 56, 
                        cpu_load = 56, 
                        free_mem = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cpus = 56, 
                        effective_cpus = 56, 
                        specialized_cpus = '0', 
                        energy = openapi_client.models.v0/0/40_acct_gather_energy.v0.0.40_acct_gather_energy(
                            average_watts = 56, 
                            base_consumed_energy = 56, 
                            consumed_energy = 56, 
                            current_watts = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            previous_consumed_energy = 56, 
                            last_collected = 56, ), 
                        external_sensors = openapi_client.models.v0/0/40_ext_sensors_data.v0.0.40_ext_sensors_data(), 
                        extra = '0', 
                        power = openapi_client.models.v0/0/40_power_mgmt_data.v0.0.40_power_mgmt_data(), 
                        features = [
                            '0'
                            ], 
                        active_features = [
                            '0'
                            ], 
                        gres = '0', 
                        gres_drained = '0', 
                        gres_used = '0', 
                        instance_id = '0', 
                        instance_type = '0', 
                        last_busy = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        mcs_label = '0', 
                        specialized_memory = 56, 
                        name = '0', 
                        next_state_after_reboot = [
                            'INVALID'
                            ], 
                        address = '0', 
                        hostname = '0', 
                        state = [
                            'INVALID'
                            ], 
                        operating_system = '0', 
                        owner = '0', 
                        partitions = [
                            '0'
                            ], 
                        port = 56, 
                        real_memory = 56, 
                        comment = '0', 
                        reason = '0', 
                        reason_changed_at = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        reason_set_by_user = '0', 
                        resume_after = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        reservation = '0', 
                        alloc_memory = 56, 
                        alloc_cpus = 56, 
                        alloc_idle_cpus = 56, 
                        tres_used = '0', 
                        tres_weighted = 1.337, 
                        slurmd_start_time = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        sockets = 56, 
                        threads = 56, 
                        temporary_disk = 56, 
                        weight = 56, 
                        tres = '0', 
                        version = '0', )
                    ], 
                last_update = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                meta = openapi_client.models.v0/0/40_openapi_meta.v0.0.40_openapi_meta(
                    plugin = openapi_client.models.v0_0_40_openapi_meta_plugin.v0_0_40_openapi_meta_plugin(
                        type = '0', 
                        name = '0', 
                        data_parser = '0', 
                        accounting_storage = '0', ), 
                    client = openapi_client.models.v0_0_40_openapi_meta_client.v0_0_40_openapi_meta_client(
                        source = '0', 
                        user = '0', 
                        group = '0', ), 
                    command = [
                        '0'
                        ], 
                    slurm = openapi_client.models.v0_0_40_openapi_meta_slurm.v0_0_40_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                            major = '0', 
                            micro = '0', 
                            minor = '0', ), 
                        release = '0', 
                        cluster = '0', ), ), 
                errors = [
                    openapi_client.models.v0/0/40_openapi_error.v0.0.40_openapi_error(
                        description = '0', 
                        error_number = 56, 
                        error = '0', 
                        source = '0', )
                    ], 
                warnings = [
                    openapi_client.models.v0/0/40_openapi_warning.v0.0.40_openapi_warning(
                        description = '0', 
                        source = '0', )
                    ]
            )
        else :
            return V0040OpenapiNodesResp(
                nodes = [
                    openapi_client.models.v0/0/40_node.v0.0.40_node(
                        architecture = '0', 
                        burstbuffer_network_address = '0', 
                        boards = 56, 
                        boot_time = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cluster_name = '0', 
                        cores = 56, 
                        specialized_cores = 56, 
                        cpu_binding = 56, 
                        cpu_load = 56, 
                        free_mem = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        cpus = 56, 
                        effective_cpus = 56, 
                        specialized_cpus = '0', 
                        energy = openapi_client.models.v0/0/40_acct_gather_energy.v0.0.40_acct_gather_energy(
                            average_watts = 56, 
                            base_consumed_energy = 56, 
                            consumed_energy = 56, 
                            current_watts = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            previous_consumed_energy = 56, 
                            last_collected = 56, ), 
                        external_sensors = openapi_client.models.v0/0/40_ext_sensors_data.v0.0.40_ext_sensors_data(), 
                        extra = '0', 
                        power = openapi_client.models.v0/0/40_power_mgmt_data.v0.0.40_power_mgmt_data(), 
                        features = [
                            '0'
                            ], 
                        active_features = [
                            '0'
                            ], 
                        gres = '0', 
                        gres_drained = '0', 
                        gres_used = '0', 
                        instance_id = '0', 
                        instance_type = '0', 
                        last_busy = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        mcs_label = '0', 
                        specialized_memory = 56, 
                        name = '0', 
                        next_state_after_reboot = [
                            'INVALID'
                            ], 
                        address = '0', 
                        hostname = '0', 
                        state = [
                            'INVALID'
                            ], 
                        operating_system = '0', 
                        owner = '0', 
                        partitions = [
                            '0'
                            ], 
                        port = 56, 
                        real_memory = 56, 
                        comment = '0', 
                        reason = '0', 
                        reason_changed_at = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        reason_set_by_user = '0', 
                        resume_after = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        reservation = '0', 
                        alloc_memory = 56, 
                        alloc_cpus = 56, 
                        alloc_idle_cpus = 56, 
                        tres_used = '0', 
                        tres_weighted = 1.337, 
                        slurmd_start_time = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        sockets = 56, 
                        threads = 56, 
                        temporary_disk = 56, 
                        weight = 56, 
                        tres = '0', 
                        version = '0', )
                    ],
                last_update = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )

    def testV0040OpenapiNodesResp(self):
        """Test V0040OpenapiNodesResp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
