# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_uint64_no_val import V0040Uint64NoVal  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040Uint64NoVal(unittest.TestCase):
    """V0040Uint64NoVal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040Uint64NoVal
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_uint64_no_val.V0040Uint64NoVal()  # noqa: E501
        if include_optional :
            return V0040Uint64NoVal(
                set = True, 
                infinite = True, 
                number = 56
            )
        else :
            return V0040Uint64NoVal(
        )

    def testV0040Uint64NoVal(self):
        """Test V0040Uint64NoVal"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
