# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_job_desc_msg import V0040JobDescMsg  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040JobDescMsg(unittest.TestCase):
    """V0040JobDescMsg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040JobDescMsg
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_job_desc_msg.V0040JobDescMsg()  # noqa: E501
        if include_optional :
            return V0040JobDescMsg(
                account = '0', 
                account_gather_frequency = '0', 
                admin_comment = '0', 
                allocation_node_list = '0', 
                allocation_node_port = 56, 
                argv = [
                    '0'
                    ], 
                array = '0', 
                batch_features = '0', 
                begin_time = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                flags = [
                    'KILL_INVALID_DEPENDENCY'
                    ], 
                burst_buffer = '0', 
                clusters = '0', 
                cluster_constraint = '0', 
                comment = '0', 
                contiguous = True, 
                container = '0', 
                container_id = '0', 
                cores_per_socket = 56, 
                core_specification = 56, 
                thread_specification = 56, 
                cpu_binding = '0', 
                cpu_binding_flags = [
                    'CPU_BIND_TO_THREADS'
                    ], 
                cpu_frequency = '0', 
                cpus_per_tres = '0', 
                crontab = openapi_client.models.v0/0/40_cron_entry.v0.0.40_cron_entry(
                    flags = [
                        'WILD_MINUTE'
                        ], 
                    minute = '0', 
                    hour = '0', 
                    day_of_month = '0', 
                    month = '0', 
                    day_of_week = '0', 
                    specification = '0', 
                    command = '0', 
                    line = openapi_client.models.v0_0_40_cron_entry_line.v0_0_40_cron_entry_line(
                        start = 56, 
                        end = 56, ), ), 
                deadline = 56, 
                delay_boot = 56, 
                dependency = '0', 
                end_time = 56, 
                environment = [
                    '0'
                    ], 
                rlimits = openapi_client.models.v0_0_40_job_desc_msg_rlimits.v0_0_40_job_desc_msg_rlimits(
                    cpu = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    fsize = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    data = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    stack = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    core = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    rss = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    nproc = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    nofile = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    memlock = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    as = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ), 
                excluded_nodes = [
                    '0'
                    ], 
                extra = '0', 
                constraints = '0', 
                group_id = '0', 
                hetjob_group = 56, 
                immediate = True, 
                job_id = 56, 
                kill_on_node_fail = True, 
                licenses = '0', 
                mail_type = [
                    'BEGIN'
                    ], 
                mail_user = '0', 
                mcs_label = '0', 
                memory_binding = '0', 
                memory_binding_type = [
                    'NONE'
                    ], 
                memory_per_tres = '0', 
                name = '0', 
                network = '0', 
                nice = 56, 
                tasks = 56, 
                open_mode = [
                    'APPEND'
                    ], 
                reserve_ports = 56, 
                overcommit = True, 
                partition = '0', 
                distribution_plane_size = 56, 
                power_flags = [
                    null
                    ], 
                prefer = '0', 
                hold = True, 
                priority = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                profile = [
                    'NOT_SET'
                    ], 
                qos = '0', 
                reboot = True, 
                required_nodes = [
                    '0'
                    ], 
                requeue = True, 
                reservation = '0', 
                script = '0', 
                shared = [
                    'none'
                    ], 
                exclusive = [
                    'true'
                    ], 
                oversubscribe = True, 
                site_factor = 56, 
                spank_environment = [
                    '0'
                    ], 
                distribution = '0', 
                time_limit = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                time_minimum = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                tres_bind = '0', 
                tres_freq = '0', 
                tres_per_job = '0', 
                tres_per_node = '0', 
                tres_per_socket = '0', 
                tres_per_task = '0', 
                user_id = '0', 
                wait_all_nodes = True, 
                kill_warning_flags = [
                    'BATCH_JOB'
                    ], 
                kill_warning_signal = '0', 
                kill_warning_delay = openapi_client.models.v0/0/40_uint16_no_val.v0.0.40_uint16_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                current_working_directory = '0', 
                cpus_per_task = 56, 
                minimum_cpus = 56, 
                maximum_cpus = 56, 
                nodes = '0', 
                minimum_nodes = 56, 
                maximum_nodes = 56, 
                minimum_boards_per_node = 56, 
                minimum_sockets_per_board = 56, 
                sockets_per_node = 56, 
                threads_per_core = 56, 
                tasks_per_node = 56, 
                tasks_per_socket = 56, 
                tasks_per_core = 56, 
                tasks_per_board = 56, 
                ntasks_per_tres = 56, 
                minimum_cpus_per_node = 56, 
                memory_per_cpu = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                memory_per_node = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                temporary_disk_per_node = 56, 
                selinux_context = '0', 
                required_switches = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                standard_error = '0', 
                standard_input = '0', 
                standard_output = '0', 
                wait_for_switch = 56, 
                wckey = '0', 
                x11 = [
                    'FORWARD_ALL_NODES'
                    ], 
                x11_magic_cookie = '0', 
                x11_target_host = '0', 
                x11_target_port = 56
            )
        else :
            return V0040JobDescMsg(
        )

    def testV0040JobDescMsg(self):
        """Test V0040JobDescMsg"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
