# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_step import V0040Step  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040Step(unittest.TestCase):
    """V0040Step unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040Step
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_step.V0040Step()  # noqa: E501
        if include_optional :
            return V0040Step(
                time = openapi_client.models.v0_0_40_step_time.v0_0_40_step_time(
                    elapsed = 56, 
                    end = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    start = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    suspended = 56, 
                    system = openapi_client.models.v0_0_40_step_time_system.v0_0_40_step_time_system(
                        seconds = 56, 
                        microseconds = 56, ), 
                    total = openapi_client.models.v0_0_40_step_time_total.v0_0_40_step_time_total(
                        seconds = 56, 
                        microseconds = 56, ), 
                    user = openapi_client.models.v0_0_40_step_time_user.v0_0_40_step_time_user(
                        seconds = 56, 
                        microseconds = 56, ), ), 
                exit_code = openapi_client.models.v0/0/40_process_exit_code_verbose.v0.0.40_process_exit_code_verbose(
                    status = [
                        'INVALID'
                        ], 
                    return_code = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = openapi_client.models.v0_0_40_process_exit_code_verbose_signal.v0_0_40_process_exit_code_verbose_signal(
                        id = openapi_client.models.v0/0/40_uint16_no_val.v0.0.40_uint16_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '0', ), ), 
                nodes = openapi_client.models.v0_0_40_step_nodes.v0_0_40_step_nodes(
                    count = 56, 
                    range = '0', 
                    list = [
                        '0'
                        ], ), 
                tasks = openapi_client.models.v0_0_40_step_tasks.v0_0_40_step_tasks(
                    count = 56, ), 
                pid = '0', 
                cpu = openapi_client.models.v0_0_40_step_cpu.v0_0_40_step_CPU(
                    requested_frequency = openapi_client.models.v0_0_40_step_cpu_requested_frequency.v0_0_40_step_CPU_requested_frequency(
                        min = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        max = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), 
                    governor = '0', ), 
                kill_request_user = '0', 
                state = [
                    'PENDING'
                    ], 
                statistics = openapi_client.models.v0_0_40_step_statistics.v0_0_40_step_statistics(
                    cpu = openapi_client.models.v0_0_40_step_statistics_cpu.v0_0_40_step_statistics_CPU(
                        actual_frequency = 56, ), 
                    energy = openapi_client.models.v0_0_40_step_statistics_energy.v0_0_40_step_statistics_energy(
                        consumed = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), ), 
                step = openapi_client.models.v0_0_40_step_step.v0_0_40_step_step(
                    id = '0', 
                    name = '0', ), 
                task = openapi_client.models.v0_0_40_step_task.v0_0_40_step_task(
                    distribution = '0', ), 
                tres = openapi_client.models.v0_0_40_step_tres.v0_0_40_step_tres(
                    requested = openapi_client.models.v0_0_40_step_tres_requested.v0_0_40_step_tres_requested(
                        max = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], 
                        min = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], 
                        average = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], 
                        total = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], ), 
                    consumed = openapi_client.models.v0_0_40_step_tres_consumed.v0_0_40_step_tres_consumed(), 
                    allocated = [
                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                            type = '0', 
                            name = '0', 
                            id = 56, 
                            count = 56, )
                        ], )
            )
        else :
            return V0040Step(
        )

    def testV0040Step(self):
        """Test V0040Step"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
