# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_assoc_max import V0040AssocMax  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040AssocMax(unittest.TestCase):
    """V0040AssocMax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040AssocMax
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_assoc_max.V0040AssocMax()  # noqa: E501
        if include_optional :
            return V0040AssocMax(
                jobs = openapi_client.models.v0_0_40_assoc_max_jobs.v0_0_40_assoc_max_jobs(
                    per = openapi_client.models.v0_0_40_assoc_max_jobs_per.v0_0_40_assoc_max_jobs_per(
                        count = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        accruing = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        submitted = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        wall_clock = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), 
                    active = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    accruing = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    total = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ), 
                tres = openapi_client.models.v0_0_40_assoc_max_tres.v0_0_40_assoc_max_tres(
                    total = [
                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                            type = '0', 
                            name = '0', 
                            id = 56, 
                            count = 56, )
                        ], 
                    group = openapi_client.models.v0_0_40_assoc_max_tres_group.v0_0_40_assoc_max_tres_group(
                        minutes = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], 
                        active = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], ), 
                    minutes = openapi_client.models.v0_0_40_assoc_max_tres_minutes.v0_0_40_assoc_max_tres_minutes(
                        total = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], 
                        per = openapi_client.models.v0_0_40_qos_limits_min_tres_per.v0_0_40_qos_limits_min_tres_per(
                            job = [
                                openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                    type = '0', 
                                    name = '0', 
                                    id = 56, 
                                    count = 56, )
                                ], ), ), 
                    per = openapi_client.models.v0_0_40_assoc_max_tres_per.v0_0_40_assoc_max_tres_per(
                        job = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], 
                        node = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], ), ), 
                per = openapi_client.models.v0_0_40_assoc_max_per.v0_0_40_assoc_max_per(
                    account = openapi_client.models.v0_0_40_assoc_max_per_account.v0_0_40_assoc_max_per_account(
                        wall_clock = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), )
            )
        else :
            return V0040AssocMax(
        )

    def testV0040AssocMax(self):
        """Test V0040AssocMax"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
