# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_job_array import V0040JobArray  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040JobArray(unittest.TestCase):
    """V0040JobArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040JobArray
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_job_array.V0040JobArray()  # noqa: E501
        if include_optional :
            return V0040JobArray(
                job_id = 56, 
                limits = openapi_client.models.v0_0_40_job_array_limits.v0_0_40_job_array_limits(
                    max = openapi_client.models.v0_0_40_job_array_limits_max.v0_0_40_job_array_limits_max(
                        running = openapi_client.models.v0_0_40_job_array_limits_max_running.v0_0_40_job_array_limits_max_running(
                            tasks = 56, ), ), ), 
                task_id = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                task = '0'
            )
        else :
            return V0040JobArray(
        )

    def testV0040JobArray(self):
        """Test V0040JobArray"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
