# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_reservation_info import V0040ReservationInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040ReservationInfo(unittest.TestCase):
    """V0040ReservationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040ReservationInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_reservation_info.V0040ReservationInfo()  # noqa: E501
        if include_optional :
            return V0040ReservationInfo(
                accounts = '0', 
                burst_buffer = '0', 
                core_count = 56, 
                core_specializations = [
                    openapi_client.models.v0/0/40_reservation_core_spec.v0.0.40_reservation_core_spec(
                        node = '0', 
                        core = '0', )
                    ], 
                end_time = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                features = '0', 
                flags = [
                    'MAINT'
                    ], 
                groups = '0', 
                licenses = '0', 
                max_start_delay = 56, 
                name = '0', 
                node_count = 56, 
                node_list = '0', 
                partition = '0', 
                purge_completed = openapi_client.models.v0_0_40_reservation_info_purge_completed.v0_0_40_reservation_info_purge_completed(
                    time = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ), 
                start_time = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                watts = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                tres = '0', 
                users = '0'
            )
        else :
            return V0040ReservationInfo(
        )

    def testV0040ReservationInfo(self):
        """Test V0040ReservationInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
