# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_openapi_slurmdbd_config_resp import V0040OpenapiSlurmdbdConfigResp  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040OpenapiSlurmdbdConfigResp(unittest.TestCase):
    """V0040OpenapiSlurmdbdConfigResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040OpenapiSlurmdbdConfigResp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_openapi_slurmdbd_config_resp.V0040OpenapiSlurmdbdConfigResp()  # noqa: E501
        if include_optional :
            return V0040OpenapiSlurmdbdConfigResp(
                clusters = [
                    openapi_client.models.v0/0/40_cluster_rec.v0.0.40_cluster_rec(
                        controller = openapi_client.models.v0_0_40_cluster_rec_controller.v0_0_40_cluster_rec_controller(
                            host = '0', 
                            port = 56, ), 
                        flags = [
                            'REGISTERING'
                            ], 
                        name = '0', 
                        nodes = '0', 
                        select_plugin = '0', 
                        associations = openapi_client.models.v0_0_40_cluster_rec_associations.v0_0_40_cluster_rec_associations(
                            root = openapi_client.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                                account = '0', 
                                cluster = '0', 
                                partition = '0', 
                                user = '0', 
                                id = 56, ), ), 
                        rpc_version = 56, 
                        tres = [
                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                type = '0', 
                                name = '0', 
                                id = 56, 
                                count = 56, )
                            ], )
                    ], 
                tres = [
                    openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                        type = '0', 
                        name = '0', 
                        id = 56, 
                        count = 56, )
                    ], 
                accounts = [
                    openapi_client.models.v0/0/40_account.v0.0.40_account(
                        associations = [
                            openapi_client.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                                account = '0', 
                                cluster = '0', 
                                partition = '0', 
                                user = '0', 
                                id = 56, )
                            ], 
                        coordinators = [
                            openapi_client.models.v0/0/40_coord.v0.0.40_coord(
                                name = '0', 
                                direct = True, )
                            ], 
                        description = '0', 
                        name = '0', 
                        organization = '0', 
                        flags = [
                            'DELETED'
                            ], )
                    ], 
                users = [
                    openapi_client.models.v0/0/40_user.v0.0.40_user(
                        administrator_level = [
                            'Not Set'
                            ], 
                        associations = [
                            openapi_client.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                                account = '0', 
                                cluster = '0', 
                                partition = '0', 
                                user = '0', 
                                id = 56, )
                            ], 
                        coordinators = [
                            openapi_client.models.v0/0/40_coord.v0.0.40_coord(
                                name = '0', 
                                direct = True, )
                            ], 
                        default = openapi_client.models.v0_0_40_user_default.v0_0_40_user_default(
                            account = '0', 
                            wckey = '0', ), 
                        flags = [
                            'NONE'
                            ], 
                        name = '0', 
                        old_name = '0', 
                        wckeys = [
                            openapi_client.models.v0/0/40_wckey.v0.0.40_wckey(
                                accounting = [
                                    openapi_client.models.v0/0/40_accounting.v0.0.40_accounting(
                                        allocated = openapi_client.models.v0_0_40_accounting_allocated.v0_0_40_accounting_allocated(
                                            seconds = 56, ), 
                                        id = 56, 
                                        start = 56, 
                                        tres = openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                            type = '0', 
                                            name = '0', 
                                            id = 56, 
                                            count = 56, ), )
                                    ], 
                                cluster = '0', 
                                id = 56, 
                                name = '0', 
                                user = '0', )
                            ], )
                    ], 
                qos = [
                    openapi_client.models.v0/0/40_qos.v0.0.40_qos(
                        description = '0', 
                        flags = [
                            'NOT_SET'
                            ], 
                        id = 56, 
                        limits = openapi_client.models.v0_0_40_qos_limits.v0_0_40_qos_limits(
                            grace_time = 56, 
                            max = openapi_client.models.v0_0_40_qos_limits_max.v0_0_40_qos_limits_max(
                                active_jobs = openapi_client.models.v0_0_40_qos_limits_max_active_jobs.v0_0_40_qos_limits_max_active_jobs(
                                    accruing = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    count = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), ), 
                                tres = openapi_client.models.v0_0_40_qos_limits_max_tres.v0_0_40_qos_limits_max_tres(
                                    total = [
                                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                            type = '0', 
                                            name = '0', 
                                            id = 56, )
                                        ], 
                                    minutes = openapi_client.models.v0_0_40_qos_limits_max_tres_minutes.v0_0_40_qos_limits_max_tres_minutes(
                                        per = openapi_client.models.v0_0_40_qos_limits_max_tres_minutes_per.v0_0_40_qos_limits_max_tres_minutes_per(
                                            qos = [
                                                openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                                    type = '0', 
                                                    name = '0', 
                                                    id = 56, )
                                                ], 
                                            job = [
                                                openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                                    type = '0', 
                                                    name = '0', 
                                                    id = 56, )
                                                ], 
                                            account = [
                                                openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                                    type = '0', 
                                                    name = '0', 
                                                    id = 56, )
                                                ], 
                                            user = [
                                                openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                                    type = '0', 
                                                    name = '0', 
                                                    id = 56, )
                                                ], ), ), 
                                    per = openapi_client.models.v0_0_40_qos_limits_max_tres_per.v0_0_40_qos_limits_max_tres_per(
                                        node = [
                                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                                type = '0', 
                                                name = '0', 
                                                id = 56, )
                                            ], ), ), 
                                wall_clock = openapi_client.models.v0_0_40_qos_limits_max_wall_clock.v0_0_40_qos_limits_max_wall_clock(), 
                                jobs = openapi_client.models.v0_0_40_qos_limits_max_jobs.v0_0_40_qos_limits_max_jobs(), 
                                accruing = openapi_client.models.v0_0_40_qos_limits_max_jobs_active_jobs.v0_0_40_qos_limits_max_jobs_active_jobs(), ), 
                            factor = openapi_client.models.v0/0/40_float64_no_val.v0.0.40_float64_no_val(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            min = openapi_client.models.v0_0_40_qos_limits_min.v0_0_40_qos_limits_min(
                                priority_threshold = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), ), ), 
                        name = '0', 
                        preempt = openapi_client.models.v0_0_40_qos_preempt.v0_0_40_qos_preempt(
                            list = [
                                '0'
                                ], 
                            mode = [
                                'DISABLED'
                                ], 
                            exempt_time = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        priority = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        usage_factor = openapi_client.models.v0/0/40_float64_no_val.v0.0.40_float64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), 
                        usage_threshold = openapi_client.models.v0/0/40_float64_no_val.v0.0.40_float64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), )
                    ], 
                wckeys = [
                    openapi_client.models.v0/0/40_wckey.v0.0.40_wckey(
                        accounting = [
                            openapi_client.models.v0/0/40_accounting.v0.0.40_accounting(
                                allocated = openapi_client.models.v0_0_40_accounting_allocated.v0_0_40_accounting_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, 
                                tres = openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                    type = '0', 
                                    name = '0', 
                                    id = 56, 
                                    count = 56, ), )
                            ], 
                        cluster = '0', 
                        id = 56, 
                        name = '0', 
                        user = '0', 
                        flags = [
                            'DELETED'
                            ], )
                    ], 
                associations = [
                    openapi_client.models.v0/0/40_assoc.v0.0.40_assoc(
                        accounting = [
                            openapi_client.models.v0/0/40_accounting.v0.0.40_accounting(
                                allocated = openapi_client.models.v0_0_40_accounting_allocated.v0_0_40_accounting_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                start = 56, 
                                tres = openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                    type = '0', 
                                    name = '0', 
                                    id = 56, 
                                    count = 56, ), )
                            ], 
                        account = '0', 
                        cluster = '0', 
                        comment = '0', 
                        default = openapi_client.models.v0_0_40_assoc_default.v0_0_40_assoc_default(
                            qos = '0', ), 
                        flags = [
                            'DELETED'
                            ], 
                        max = openapi_client.models.v0_0_40_assoc_max.v0_0_40_assoc_max(
                            jobs = openapi_client.models.v0_0_40_assoc_max_jobs.v0_0_40_assoc_max_jobs(
                                per = openapi_client.models.v0_0_40_assoc_max_jobs_per.v0_0_40_assoc_max_jobs_per(
                                    count = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    accruing = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    submitted = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), 
                                    wall_clock = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), ), 
                                active = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                accruing = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                total = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), ), 
                            tres = openapi_client.models.v0_0_40_assoc_max_tres.v0_0_40_assoc_max_tres(
                                group = openapi_client.models.v0_0_40_assoc_max_tres_group.v0_0_40_assoc_max_tres_group(
                                    minutes = [
                                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                            type = '0', 
                                            name = '0', 
                                            id = 56, )
                                        ], ), 
                                minutes = openapi_client.models.v0_0_40_assoc_max_tres_minutes.v0_0_40_assoc_max_tres_minutes(), ), 
                            per = openapi_client.models.v0_0_40_assoc_max_per.v0_0_40_assoc_max_per(
                                account = openapi_client.models.v0_0_40_assoc_max_per_account.v0_0_40_assoc_max_per_account(), ), ), 
                        id = openapi_client.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                            cluster = '0', 
                            partition = '0', 
                            user = '0', ), 
                        is_default = True, 
                        lineage = '0', 
                        min = openapi_client.models.v0_0_40_assoc_min.v0_0_40_assoc_min(
                            priority_threshold = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        parent_account = '0', 
                        partition = '0', 
                        priority = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        qos = [
                            '0'
                            ], 
                        shares_raw = 56, 
                        user = '0', )
                    ], 
                instances = [
                    openapi_client.models.v0/0/40_instance.v0.0.40_instance(
                        cluster = '0', 
                        extra = '0', 
                        instance_id = '0', 
                        instance_type = '0', 
                        node_name = '0', 
                        time = openapi_client.models.v0_0_40_instance_time.v0_0_40_instance_time(
                            time_end = 56, 
                            time_start = 56, ), )
                    ], 
                meta = openapi_client.models.v0/0/40_openapi_meta.v0.0.40_openapi_meta(
                    plugin = openapi_client.models.v0_0_40_openapi_meta_plugin.v0_0_40_openapi_meta_plugin(
                        type = '0', 
                        name = '0', 
                        data_parser = '0', 
                        accounting_storage = '0', ), 
                    client = openapi_client.models.v0_0_40_openapi_meta_client.v0_0_40_openapi_meta_client(
                        source = '0', 
                        user = '0', 
                        group = '0', ), 
                    command = [
                        '0'
                        ], 
                    slurm = openapi_client.models.v0_0_40_openapi_meta_slurm.v0_0_40_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                            major = '0', 
                            micro = '0', 
                            minor = '0', ), 
                        release = '0', 
                        cluster = '0', ), ), 
                errors = [
                    openapi_client.models.v0/0/40_openapi_error.v0.0.40_openapi_error(
                        description = '0', 
                        error_number = 56, 
                        error = '0', 
                        source = '0', )
                    ], 
                warnings = [
                    openapi_client.models.v0/0/40_openapi_warning.v0.0.40_openapi_warning(
                        description = '0', 
                        source = '0', )
                    ]
            )
        else :
            return V0040OpenapiSlurmdbdConfigResp(
        )

    def testV0040OpenapiSlurmdbdConfigResp(self):
        """Test V0040OpenapiSlurmdbdConfigResp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
