# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_openapi_slurmdbd_jobs_resp import V0040OpenapiSlurmdbdJobsResp  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040OpenapiSlurmdbdJobsResp(unittest.TestCase):
    """V0040OpenapiSlurmdbdJobsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040OpenapiSlurmdbdJobsResp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_openapi_slurmdbd_jobs_resp.V0040OpenapiSlurmdbdJobsResp()  # noqa: E501
        if include_optional :
            return V0040OpenapiSlurmdbdJobsResp(
                jobs = [
                    openapi_client.models.v0/0/40_job.v0.0.40_job(
                        account = '0', 
                        comment = openapi_client.models.v0_0_40_job_comment.v0_0_40_job_comment(
                            administrator = '0', 
                            job = '0', 
                            system = '0', ), 
                        allocation_nodes = 56, 
                        array = openapi_client.models.v0_0_40_job_array.v0_0_40_job_array(
                            job_id = 56, 
                            limits = openapi_client.models.v0_0_40_job_array_limits.v0_0_40_job_array_limits(
                                max = openapi_client.models.v0_0_40_job_array_limits_max.v0_0_40_job_array_limits_max(
                                    running = openapi_client.models.v0_0_40_job_array_limits_max_running.v0_0_40_job_array_limits_max_running(
                                        tasks = 56, ), ), ), 
                            task_id = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            task = '0', ), 
                        association = openapi_client.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                            account = '0', 
                            cluster = '0', 
                            partition = '0', 
                            user = '0', 
                            id = 56, ), 
                        block = '0', 
                        cluster = '0', 
                        constraints = '0', 
                        container = '0', 
                        derived_exit_code = openapi_client.models.v0/0/40_process_exit_code_verbose.v0.0.40_process_exit_code_verbose(
                            status = [
                                'INVALID'
                                ], 
                            return_code = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            signal = openapi_client.models.v0_0_40_process_exit_code_verbose_signal.v0_0_40_process_exit_code_verbose_signal(
                                id = openapi_client.models.v0/0/40_uint16_no_val.v0.0.40_uint16_no_val(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                name = '0', ), ), 
                        time = openapi_client.models.v0_0_40_job_time.v0_0_40_job_time(
                            elapsed = 56, 
                            eligible = 56, 
                            end = 56, 
                            start = 56, 
                            submission = 56, 
                            suspended = 56, 
                            system = openapi_client.models.v0_0_40_job_time_system.v0_0_40_job_time_system(
                                seconds = 56, 
                                microseconds = 56, ), 
                            limit = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            total = openapi_client.models.v0_0_40_job_time_total.v0_0_40_job_time_total(
                                seconds = 56, 
                                microseconds = 56, ), 
                            user = openapi_client.models.v0_0_40_job_time_user.v0_0_40_job_time_user(
                                seconds = 56, 
                                microseconds = 56, ), ), 
                        exit_code = openapi_client.models.v0/0/40_process_exit_code_verbose.v0.0.40_process_exit_code_verbose(), 
                        extra = '0', 
                        failed_node = '0', 
                        flags = [
                            'NONE'
                            ], 
                        group = '0', 
                        het = openapi_client.models.v0_0_40_job_het.v0_0_40_job_het(
                            job_id = 56, 
                            job_offset = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        job_id = 56, 
                        name = '0', 
                        licenses = '0', 
                        mcs = openapi_client.models.v0_0_40_job_mcs.v0_0_40_job_mcs(
                            label = '0', ), 
                        nodes = '0', 
                        partition = '0', 
                        hold = True, 
                        priority = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        qos = '0', 
                        required = openapi_client.models.v0_0_40_job_required.v0_0_40_job_required(
                            cp_us = 56, 
                            memory_per_cpu = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            memory_per_node = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        kill_request_user = '0', 
                        reservation = openapi_client.models.v0_0_40_job_reservation.v0_0_40_job_reservation(
                            name = '0', ), 
                        script = '0', 
                        state = openapi_client.models.v0_0_40_job_state.v0_0_40_job_state(
                            current = [
                                'PENDING'
                                ], 
                            reason = '0', ), 
                        steps = [
                            openapi_client.models.v0/0/40_step.v0.0.40_step(
                                nodes = openapi_client.models.v0_0_40_step_nodes.v0_0_40_step_nodes(
                                    count = 56, 
                                    range = '0', 
                                    list = [
                                        '0'
                                        ], ), 
                                tasks = openapi_client.models.v0_0_40_step_tasks.v0_0_40_step_tasks(
                                    count = 56, ), 
                                pid = '0', 
                                cpu = openapi_client.models.v0_0_40_step_cpu.v0_0_40_step_CPU(
                                    requested_frequency = openapi_client.models.v0_0_40_step_cpu_requested_frequency.v0_0_40_step_CPU_requested_frequency(
                                        min = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), ), 
                                    governor = '0', ), 
                                kill_request_user = '0', 
                                statistics = openapi_client.models.v0_0_40_step_statistics.v0_0_40_step_statistics(
                                    energy = openapi_client.models.v0_0_40_step_statistics_energy.v0_0_40_step_statistics_energy(
                                        consumed = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), ), ), 
                                step = openapi_client.models.v0_0_40_step_step.v0_0_40_step_step(
                                    name = '0', ), 
                                task = openapi_client.models.v0_0_40_step_task.v0_0_40_step_task(
                                    distribution = '0', ), 
                                tres = openapi_client.models.v0_0_40_step_tres.v0_0_40_step_tres(
                                    requested = openapi_client.models.v0_0_40_step_tres_requested.v0_0_40_step_tres_requested(
                                        average = [
                                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                                type = '0', 
                                                name = '0', 
                                                count = 56, )
                                            ], ), 
                                    allocated = [
                                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                            type = '0', 
                                            name = '0', 
                                            count = 56, )
                                        ], ), )
                            ], 
                        submit_line = '0', 
                        tres = openapi_client.models.v0_0_40_job_tres.v0_0_40_job_tres(), 
                        used_gres = '0', 
                        user = '0', 
                        wckey = openapi_client.models.v0/0/40_wckey_tag_struct.v0.0.40_wckey_tag_struct(
                            wckey = '0', 
                            flags = [
                                'ASSIGNED_DEFAULT'
                                ], ), 
                        working_directory = '0', )
                    ], 
                meta = openapi_client.models.v0/0/40_openapi_meta.v0.0.40_openapi_meta(
                    plugin = openapi_client.models.v0_0_40_openapi_meta_plugin.v0_0_40_openapi_meta_plugin(
                        type = '0', 
                        name = '0', 
                        data_parser = '0', 
                        accounting_storage = '0', ), 
                    client = openapi_client.models.v0_0_40_openapi_meta_client.v0_0_40_openapi_meta_client(
                        source = '0', 
                        user = '0', 
                        group = '0', ), 
                    command = [
                        '0'
                        ], 
                    slurm = openapi_client.models.v0_0_40_openapi_meta_slurm.v0_0_40_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                            major = '0', 
                            micro = '0', 
                            minor = '0', ), 
                        release = '0', 
                        cluster = '0', ), ), 
                errors = [
                    openapi_client.models.v0/0/40_openapi_error.v0.0.40_openapi_error(
                        description = '0', 
                        error_number = 56, 
                        error = '0', 
                        source = '0', )
                    ], 
                warnings = [
                    openapi_client.models.v0/0/40_openapi_warning.v0.0.40_openapi_warning(
                        description = '0', 
                        source = '0', )
                    ]
            )
        else :
            return V0040OpenapiSlurmdbdJobsResp(
                jobs = [
                    openapi_client.models.v0/0/40_job.v0.0.40_job(
                        account = '0', 
                        comment = openapi_client.models.v0_0_40_job_comment.v0_0_40_job_comment(
                            administrator = '0', 
                            job = '0', 
                            system = '0', ), 
                        allocation_nodes = 56, 
                        array = openapi_client.models.v0_0_40_job_array.v0_0_40_job_array(
                            job_id = 56, 
                            limits = openapi_client.models.v0_0_40_job_array_limits.v0_0_40_job_array_limits(
                                max = openapi_client.models.v0_0_40_job_array_limits_max.v0_0_40_job_array_limits_max(
                                    running = openapi_client.models.v0_0_40_job_array_limits_max_running.v0_0_40_job_array_limits_max_running(
                                        tasks = 56, ), ), ), 
                            task_id = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            task = '0', ), 
                        association = openapi_client.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                            account = '0', 
                            cluster = '0', 
                            partition = '0', 
                            user = '0', 
                            id = 56, ), 
                        block = '0', 
                        cluster = '0', 
                        constraints = '0', 
                        container = '0', 
                        derived_exit_code = openapi_client.models.v0/0/40_process_exit_code_verbose.v0.0.40_process_exit_code_verbose(
                            status = [
                                'INVALID'
                                ], 
                            return_code = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            signal = openapi_client.models.v0_0_40_process_exit_code_verbose_signal.v0_0_40_process_exit_code_verbose_signal(
                                id = openapi_client.models.v0/0/40_uint16_no_val.v0.0.40_uint16_no_val(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                name = '0', ), ), 
                        time = openapi_client.models.v0_0_40_job_time.v0_0_40_job_time(
                            elapsed = 56, 
                            eligible = 56, 
                            end = 56, 
                            start = 56, 
                            submission = 56, 
                            suspended = 56, 
                            system = openapi_client.models.v0_0_40_job_time_system.v0_0_40_job_time_system(
                                seconds = 56, 
                                microseconds = 56, ), 
                            limit = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            total = openapi_client.models.v0_0_40_job_time_total.v0_0_40_job_time_total(
                                seconds = 56, 
                                microseconds = 56, ), 
                            user = openapi_client.models.v0_0_40_job_time_user.v0_0_40_job_time_user(
                                seconds = 56, 
                                microseconds = 56, ), ), 
                        exit_code = openapi_client.models.v0/0/40_process_exit_code_verbose.v0.0.40_process_exit_code_verbose(), 
                        extra = '0', 
                        failed_node = '0', 
                        flags = [
                            'NONE'
                            ], 
                        group = '0', 
                        het = openapi_client.models.v0_0_40_job_het.v0_0_40_job_het(
                            job_id = 56, 
                            job_offset = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        job_id = 56, 
                        name = '0', 
                        licenses = '0', 
                        mcs = openapi_client.models.v0_0_40_job_mcs.v0_0_40_job_mcs(
                            label = '0', ), 
                        nodes = '0', 
                        partition = '0', 
                        hold = True, 
                        priority = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        qos = '0', 
                        required = openapi_client.models.v0_0_40_job_required.v0_0_40_job_required(
                            cp_us = 56, 
                            memory_per_cpu = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            memory_per_node = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        kill_request_user = '0', 
                        reservation = openapi_client.models.v0_0_40_job_reservation.v0_0_40_job_reservation(
                            name = '0', ), 
                        script = '0', 
                        state = openapi_client.models.v0_0_40_job_state.v0_0_40_job_state(
                            current = [
                                'PENDING'
                                ], 
                            reason = '0', ), 
                        steps = [
                            openapi_client.models.v0/0/40_step.v0.0.40_step(
                                nodes = openapi_client.models.v0_0_40_step_nodes.v0_0_40_step_nodes(
                                    count = 56, 
                                    range = '0', 
                                    list = [
                                        '0'
                                        ], ), 
                                tasks = openapi_client.models.v0_0_40_step_tasks.v0_0_40_step_tasks(
                                    count = 56, ), 
                                pid = '0', 
                                cpu = openapi_client.models.v0_0_40_step_cpu.v0_0_40_step_CPU(
                                    requested_frequency = openapi_client.models.v0_0_40_step_cpu_requested_frequency.v0_0_40_step_CPU_requested_frequency(
                                        min = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), ), 
                                    governor = '0', ), 
                                kill_request_user = '0', 
                                statistics = openapi_client.models.v0_0_40_step_statistics.v0_0_40_step_statistics(
                                    energy = openapi_client.models.v0_0_40_step_statistics_energy.v0_0_40_step_statistics_energy(
                                        consumed = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), ), ), 
                                step = openapi_client.models.v0_0_40_step_step.v0_0_40_step_step(
                                    name = '0', ), 
                                task = openapi_client.models.v0_0_40_step_task.v0_0_40_step_task(
                                    distribution = '0', ), 
                                tres = openapi_client.models.v0_0_40_step_tres.v0_0_40_step_tres(
                                    requested = openapi_client.models.v0_0_40_step_tres_requested.v0_0_40_step_tres_requested(
                                        average = [
                                            openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                                type = '0', 
                                                name = '0', 
                                                count = 56, )
                                            ], ), 
                                    allocated = [
                                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                                            type = '0', 
                                            name = '0', 
                                            count = 56, )
                                        ], ), )
                            ], 
                        submit_line = '0', 
                        tres = openapi_client.models.v0_0_40_job_tres.v0_0_40_job_tres(), 
                        used_gres = '0', 
                        user = '0', 
                        wckey = openapi_client.models.v0/0/40_wckey_tag_struct.v0.0.40_wckey_tag_struct(
                            wckey = '0', 
                            flags = [
                                'ASSIGNED_DEFAULT'
                                ], ), 
                        working_directory = '0', )
                    ],
        )

    def testV0040OpenapiSlurmdbdJobsResp(self):
        """Test V0040OpenapiSlurmdbdJobsResp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
