# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_account import V0040Account  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040Account(unittest.TestCase):
    """V0040Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040Account
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_account.V0040Account()  # noqa: E501
        if include_optional :
            return V0040Account(
                associations = [
                    openapi_client.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                        account = '0', 
                        cluster = '0', 
                        partition = '0', 
                        user = '0', 
                        id = 56, )
                    ], 
                coordinators = [
                    openapi_client.models.v0/0/40_coord.v0.0.40_coord(
                        name = '0', 
                        direct = True, )
                    ], 
                description = '0', 
                name = '0', 
                organization = '0', 
                flags = [
                    'DELETED'
                    ]
            )
        else :
            return V0040Account(
                description = '0',
                name = '0',
                organization = '0',
        )

    def testV0040Account(self):
        """Test V0040Account"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
