# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_openapi_meta_slurm import V0040OpenapiMetaSlurm  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040OpenapiMetaSlurm(unittest.TestCase):
    """V0040OpenapiMetaSlurm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040OpenapiMetaSlurm
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_openapi_meta_slurm.V0040OpenapiMetaSlurm()  # noqa: E501
        if include_optional :
            return V0040OpenapiMetaSlurm(
                version = openapi_client.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                    major = '0', 
                    micro = '0', 
                    minor = '0', ), 
                release = '0', 
                cluster = '0'
            )
        else :
            return V0040OpenapiMetaSlurm(
        )

    def testV0040OpenapiMetaSlurm(self):
        """Test V0040OpenapiMetaSlurm"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
