# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v0040_openapi_licenses_resp import V0040OpenapiLicensesResp  # noqa: E501
from openapi_client.rest import ApiException

class TestV0040OpenapiLicensesResp(unittest.TestCase):
    """V0040OpenapiLicensesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V0040OpenapiLicensesResp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v0040_openapi_licenses_resp.V0040OpenapiLicensesResp()  # noqa: E501
        if include_optional :
            return V0040OpenapiLicensesResp(
                licenses = [
                    openapi_client.models.v0/0/40_license.v0.0.40_license(
                        license_name = '0', 
                        total = 56, 
                        used = 56, 
                        free = 56, 
                        remote = True, 
                        reserved = 56, 
                        last_consumed = 56, 
                        last_deficit = 56, 
                        last_update = 56, )
                    ], 
                last_update = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ), 
                meta = openapi_client.models.v0/0/40_openapi_meta.v0.0.40_openapi_meta(
                    plugin = openapi_client.models.v0_0_40_openapi_meta_plugin.v0_0_40_openapi_meta_plugin(
                        type = '0', 
                        name = '0', 
                        data_parser = '0', 
                        accounting_storage = '0', ), 
                    client = openapi_client.models.v0_0_40_openapi_meta_client.v0_0_40_openapi_meta_client(
                        source = '0', 
                        user = '0', 
                        group = '0', ), 
                    command = [
                        '0'
                        ], 
                    slurm = openapi_client.models.v0_0_40_openapi_meta_slurm.v0_0_40_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                            major = '0', 
                            micro = '0', 
                            minor = '0', ), 
                        release = '0', 
                        cluster = '0', ), ), 
                errors = [
                    openapi_client.models.v0/0/40_openapi_error.v0.0.40_openapi_error(
                        description = '0', 
                        error_number = 56, 
                        error = '0', 
                        source = '0', )
                    ], 
                warnings = [
                    openapi_client.models.v0/0/40_openapi_warning.v0.0.40_openapi_warning(
                        description = '0', 
                        source = '0', )
                    ]
            )
        else :
            return V0040OpenapiLicensesResp(
                licenses = [
                    openapi_client.models.v0/0/40_license.v0.0.40_license(
                        license_name = '0', 
                        total = 56, 
                        used = 56, 
                        free = 56, 
                        remote = True, 
                        reserved = 56, 
                        last_consumed = 56, 
                        last_deficit = 56, 
                        last_update = 56, )
                    ],
                last_update = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )

    def testV0040OpenapiLicensesResp(self):
        """Test V0040OpenapiLicensesResp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
