# coding: utf-8

# flake8: noqa
"""
    Slurm REST API (Partial)

    A partial OpenAPI specification for the Slurm REST API, focusing on user and account management. This specification describes the endpoints used by the Python script to create and manage Slurm users and accounts.   # noqa: E501

    The version of the OpenAPI document: 0.0.38
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.inline_object import InlineObject
from openapi_client.models.inline_object1 import InlineObject1
from openapi_client.models.inline_response200 import InlineResponse200
from openapi_client.models.inline_response2001 import InlineResponse2001
from openapi_client.models.inline_response2002 import InlineResponse2002
from openapi_client.models.new_slurm_account import NewSlurmAccount
from openapi_client.models.new_slurm_user import NewSlurmUser
from openapi_client.models.slurm_account import SlurmAccount
from openapi_client.models.slurm_user import SlurmUser
