# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040OpenapiJobSubmitResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'result': 'V0040JobSubmitResponseMsg',
        'job_id': 'int',
        'step_id': 'str',
        'job_submit_user_msg': 'str',
        'meta': 'V0040OpenapiMeta',
        'errors': 'list[V0040OpenapiError]',
        'warnings': 'list[V0040OpenapiWarning]'
    }

    attribute_map = {
        'result': 'result',
        'job_id': 'job_id',
        'step_id': 'step_id',
        'job_submit_user_msg': 'job_submit_user_msg',
        'meta': 'meta',
        'errors': 'errors',
        'warnings': 'warnings'
    }

    def __init__(self, result=None, job_id=None, step_id=None, job_submit_user_msg=None, meta=None, errors=None, warnings=None, local_vars_configuration=None):  # noqa: E501
        """V0040OpenapiJobSubmitResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._result = None
        self._job_id = None
        self._step_id = None
        self._job_submit_user_msg = None
        self._meta = None
        self._errors = None
        self._warnings = None
        self.discriminator = None

        if result is not None:
            self.result = result
        if job_id is not None:
            self.job_id = job_id
        if step_id is not None:
            self.step_id = step_id
        if job_submit_user_msg is not None:
            self.job_submit_user_msg = job_submit_user_msg
        if meta is not None:
            self.meta = meta
        if errors is not None:
            self.errors = errors
        if warnings is not None:
            self.warnings = warnings

    @property
    def result(self):
        """Gets the result of this V0040OpenapiJobSubmitResponse.  # noqa: E501


        :return: The result of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :rtype: V0040JobSubmitResponseMsg
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this V0040OpenapiJobSubmitResponse.


        :param result: The result of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :type: V0040JobSubmitResponseMsg
        """

        self._result = result

    @property
    def job_id(self):
        """Gets the job_id of this V0040OpenapiJobSubmitResponse.  # noqa: E501

        Submitted Job ID  # noqa: E501

        :return: The job_id of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this V0040OpenapiJobSubmitResponse.

        Submitted Job ID  # noqa: E501

        :param job_id: The job_id of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def step_id(self):
        """Gets the step_id of this V0040OpenapiJobSubmitResponse.  # noqa: E501

        Submitted Step ID  # noqa: E501

        :return: The step_id of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :rtype: str
        """
        return self._step_id

    @step_id.setter
    def step_id(self, step_id):
        """Sets the step_id of this V0040OpenapiJobSubmitResponse.

        Submitted Step ID  # noqa: E501

        :param step_id: The step_id of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :type: str
        """

        self._step_id = step_id

    @property
    def job_submit_user_msg(self):
        """Gets the job_submit_user_msg of this V0040OpenapiJobSubmitResponse.  # noqa: E501

        job submision user message  # noqa: E501

        :return: The job_submit_user_msg of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :rtype: str
        """
        return self._job_submit_user_msg

    @job_submit_user_msg.setter
    def job_submit_user_msg(self, job_submit_user_msg):
        """Sets the job_submit_user_msg of this V0040OpenapiJobSubmitResponse.

        job submision user message  # noqa: E501

        :param job_submit_user_msg: The job_submit_user_msg of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :type: str
        """

        self._job_submit_user_msg = job_submit_user_msg

    @property
    def meta(self):
        """Gets the meta of this V0040OpenapiJobSubmitResponse.  # noqa: E501


        :return: The meta of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :rtype: V0040OpenapiMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this V0040OpenapiJobSubmitResponse.


        :param meta: The meta of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :type: V0040OpenapiMeta
        """

        self._meta = meta

    @property
    def errors(self):
        """Gets the errors of this V0040OpenapiJobSubmitResponse.  # noqa: E501


        :return: The errors of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :rtype: list[V0040OpenapiError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this V0040OpenapiJobSubmitResponse.


        :param errors: The errors of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :type: list[V0040OpenapiError]
        """

        self._errors = errors

    @property
    def warnings(self):
        """Gets the warnings of this V0040OpenapiJobSubmitResponse.  # noqa: E501


        :return: The warnings of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :rtype: list[V0040OpenapiWarning]
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this V0040OpenapiJobSubmitResponse.


        :param warnings: The warnings of this V0040OpenapiJobSubmitResponse.  # noqa: E501
        :type: list[V0040OpenapiWarning]
        """

        self._warnings = warnings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040OpenapiJobSubmitResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040OpenapiJobSubmitResponse):
            return True

        return self.to_dict() != other.to_dict()
