# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040PartitionInfoPriority(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'job_factor': 'int',
        'tier': 'int'
    }

    attribute_map = {
        'job_factor': 'job_factor',
        'tier': 'tier'
    }

    def __init__(self, job_factor=None, tier=None, local_vars_configuration=None):  # noqa: E501
        """V0040PartitionInfoPriority - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._job_factor = None
        self._tier = None
        self.discriminator = None

        if job_factor is not None:
            self.job_factor = job_factor
        if tier is not None:
            self.tier = tier

    @property
    def job_factor(self):
        """Gets the job_factor of this V0040PartitionInfoPriority.  # noqa: E501

        PriorityJobFactor  # noqa: E501

        :return: The job_factor of this V0040PartitionInfoPriority.  # noqa: E501
        :rtype: int
        """
        return self._job_factor

    @job_factor.setter
    def job_factor(self, job_factor):
        """Sets the job_factor of this V0040PartitionInfoPriority.

        PriorityJobFactor  # noqa: E501

        :param job_factor: The job_factor of this V0040PartitionInfoPriority.  # noqa: E501
        :type: int
        """

        self._job_factor = job_factor

    @property
    def tier(self):
        """Gets the tier of this V0040PartitionInfoPriority.  # noqa: E501

        PriorityTier  # noqa: E501

        :return: The tier of this V0040PartitionInfoPriority.  # noqa: E501
        :rtype: int
        """
        return self._tier

    @tier.setter
    def tier(self, tier):
        """Sets the tier of this V0040PartitionInfoPriority.

        PriorityTier  # noqa: E501

        :param tier: The tier of this V0040PartitionInfoPriority.  # noqa: E501
        :type: int
        """

        self._tier = tier

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040PartitionInfoPriority):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040PartitionInfoPriority):
            return True

        return self.to_dict() != other.to_dict()
