# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040PartitionInfoTimeouts(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'resume': 'V0040Uint16NoVal',
        'suspend': 'V0040Uint16NoVal'
    }

    attribute_map = {
        'resume': 'resume',
        'suspend': 'suspend'
    }

    def __init__(self, resume=None, suspend=None, local_vars_configuration=None):  # noqa: E501
        """V0040PartitionInfoTimeouts - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._resume = None
        self._suspend = None
        self.discriminator = None

        if resume is not None:
            self.resume = resume
        if suspend is not None:
            self.suspend = suspend

    @property
    def resume(self):
        """Gets the resume of this V0040PartitionInfoTimeouts.  # noqa: E501


        :return: The resume of this V0040PartitionInfoTimeouts.  # noqa: E501
        :rtype: V0040Uint16NoVal
        """
        return self._resume

    @resume.setter
    def resume(self, resume):
        """Sets the resume of this V0040PartitionInfoTimeouts.


        :param resume: The resume of this V0040PartitionInfoTimeouts.  # noqa: E501
        :type: V0040Uint16NoVal
        """

        self._resume = resume

    @property
    def suspend(self):
        """Gets the suspend of this V0040PartitionInfoTimeouts.  # noqa: E501


        :return: The suspend of this V0040PartitionInfoTimeouts.  # noqa: E501
        :rtype: V0040Uint16NoVal
        """
        return self._suspend

    @suspend.setter
    def suspend(self, suspend):
        """Sets the suspend of this V0040PartitionInfoTimeouts.


        :param suspend: The suspend of this V0040PartitionInfoTimeouts.  # noqa: E501
        :type: V0040Uint16NoVal
        """

        self._suspend = suspend

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040PartitionInfoTimeouts):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040PartitionInfoTimeouts):
            return True

        return self.to_dict() != other.to_dict()
