# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040PartitionInfoQos(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'allowed': 'str',
        'deny': 'str',
        'assigned': 'str'
    }

    attribute_map = {
        'allowed': 'allowed',
        'deny': 'deny',
        'assigned': 'assigned'
    }

    def __init__(self, allowed=None, deny=None, assigned=None, local_vars_configuration=None):  # noqa: E501
        """V0040PartitionInfoQos - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._allowed = None
        self._deny = None
        self._assigned = None
        self.discriminator = None

        if allowed is not None:
            self.allowed = allowed
        if deny is not None:
            self.deny = deny
        if assigned is not None:
            self.assigned = assigned

    @property
    def allowed(self):
        """Gets the allowed of this V0040PartitionInfoQos.  # noqa: E501

        AllowQOS  # noqa: E501

        :return: The allowed of this V0040PartitionInfoQos.  # noqa: E501
        :rtype: str
        """
        return self._allowed

    @allowed.setter
    def allowed(self, allowed):
        """Sets the allowed of this V0040PartitionInfoQos.

        AllowQOS  # noqa: E501

        :param allowed: The allowed of this V0040PartitionInfoQos.  # noqa: E501
        :type: str
        """

        self._allowed = allowed

    @property
    def deny(self):
        """Gets the deny of this V0040PartitionInfoQos.  # noqa: E501

        DenyQOS  # noqa: E501

        :return: The deny of this V0040PartitionInfoQos.  # noqa: E501
        :rtype: str
        """
        return self._deny

    @deny.setter
    def deny(self, deny):
        """Sets the deny of this V0040PartitionInfoQos.

        DenyQOS  # noqa: E501

        :param deny: The deny of this V0040PartitionInfoQos.  # noqa: E501
        :type: str
        """

        self._deny = deny

    @property
    def assigned(self):
        """Gets the assigned of this V0040PartitionInfoQos.  # noqa: E501

        QOS  # noqa: E501

        :return: The assigned of this V0040PartitionInfoQos.  # noqa: E501
        :rtype: str
        """
        return self._assigned

    @assigned.setter
    def assigned(self, assigned):
        """Sets the assigned of this V0040PartitionInfoQos.

        QOS  # noqa: E501

        :param assigned: The assigned of this V0040PartitionInfoQos.  # noqa: E501
        :type: str
        """

        self._assigned = assigned

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040PartitionInfoQos):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040PartitionInfoQos):
            return True

        return self.to_dict() != other.to_dict()
