# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040OpenapiSlurmdbdQosResp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'qos': 'list[V0040Qos]',
        'meta': 'V0040OpenapiMeta',
        'errors': 'list[V0040OpenapiError]',
        'warnings': 'list[V0040OpenapiWarning]'
    }

    attribute_map = {
        'qos': 'qos',
        'meta': 'meta',
        'errors': 'errors',
        'warnings': 'warnings'
    }

    def __init__(self, qos=None, meta=None, errors=None, warnings=None, local_vars_configuration=None):  # noqa: E501
        """V0040OpenapiSlurmdbdQosResp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._qos = None
        self._meta = None
        self._errors = None
        self._warnings = None
        self.discriminator = None

        self.qos = qos
        if meta is not None:
            self.meta = meta
        if errors is not None:
            self.errors = errors
        if warnings is not None:
            self.warnings = warnings

    @property
    def qos(self):
        """Gets the qos of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501


        :return: The qos of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :rtype: list[V0040Qos]
        """
        return self._qos

    @qos.setter
    def qos(self, qos):
        """Sets the qos of this V0040OpenapiSlurmdbdQosResp.


        :param qos: The qos of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :type: list[V0040Qos]
        """
        if self.local_vars_configuration.client_side_validation and qos is None:  # noqa: E501
            raise ValueError("Invalid value for `qos`, must not be `None`")  # noqa: E501

        self._qos = qos

    @property
    def meta(self):
        """Gets the meta of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501


        :return: The meta of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :rtype: V0040OpenapiMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this V0040OpenapiSlurmdbdQosResp.


        :param meta: The meta of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :type: V0040OpenapiMeta
        """

        self._meta = meta

    @property
    def errors(self):
        """Gets the errors of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501


        :return: The errors of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :rtype: list[V0040OpenapiError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this V0040OpenapiSlurmdbdQosResp.


        :param errors: The errors of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :type: list[V0040OpenapiError]
        """

        self._errors = errors

    @property
    def warnings(self):
        """Gets the warnings of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501


        :return: The warnings of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :rtype: list[V0040OpenapiWarning]
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this V0040OpenapiSlurmdbdQosResp.


        :param warnings: The warnings of this V0040OpenapiSlurmdbdQosResp.  # noqa: E501
        :type: list[V0040OpenapiWarning]
        """

        self._warnings = warnings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040OpenapiSlurmdbdQosResp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040OpenapiSlurmdbdQosResp):
            return True

        return self.to_dict() != other.to_dict()
