# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040StatsRpc(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'rpc': 'str',
        'count': 'int',
        'time': 'V0040StatsRpcTime'
    }

    attribute_map = {
        'rpc': 'rpc',
        'count': 'count',
        'time': 'time'
    }

    def __init__(self, rpc=None, count=None, time=None, local_vars_configuration=None):  # noqa: E501
        """V0040StatsRpc - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._rpc = None
        self._count = None
        self._time = None
        self.discriminator = None

        if rpc is not None:
            self.rpc = rpc
        if count is not None:
            self.count = count
        if time is not None:
            self.time = time

    @property
    def rpc(self):
        """Gets the rpc of this V0040StatsRpc.  # noqa: E501

        RPC type  # noqa: E501

        :return: The rpc of this V0040StatsRpc.  # noqa: E501
        :rtype: str
        """
        return self._rpc

    @rpc.setter
    def rpc(self, rpc):
        """Sets the rpc of this V0040StatsRpc.

        RPC type  # noqa: E501

        :param rpc: The rpc of this V0040StatsRpc.  # noqa: E501
        :type: str
        """

        self._rpc = rpc

    @property
    def count(self):
        """Gets the count of this V0040StatsRpc.  # noqa: E501

        Number of RPCs processed  # noqa: E501

        :return: The count of this V0040StatsRpc.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this V0040StatsRpc.

        Number of RPCs processed  # noqa: E501

        :param count: The count of this V0040StatsRpc.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def time(self):
        """Gets the time of this V0040StatsRpc.  # noqa: E501


        :return: The time of this V0040StatsRpc.  # noqa: E501
        :rtype: V0040StatsRpcTime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this V0040StatsRpc.


        :param time: The time of this V0040StatsRpc.  # noqa: E501
        :type: V0040StatsRpcTime
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040StatsRpc):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040StatsRpc):
            return True

        return self.to_dict() != other.to_dict()
