# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040QosLimits(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'grace_time': 'int',
        'max': 'V0040QosLimitsMax',
        'factor': 'V0040Float64NoVal',
        'min': 'V0040QosLimitsMin'
    }

    attribute_map = {
        'grace_time': 'grace_time',
        'max': 'max',
        'factor': 'factor',
        'min': 'min'
    }

    def __init__(self, grace_time=None, max=None, factor=None, min=None, local_vars_configuration=None):  # noqa: E501
        """V0040QosLimits - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._grace_time = None
        self._max = None
        self._factor = None
        self._min = None
        self.discriminator = None

        if grace_time is not None:
            self.grace_time = grace_time
        if max is not None:
            self.max = max
        if factor is not None:
            self.factor = factor
        if min is not None:
            self.min = min

    @property
    def grace_time(self):
        """Gets the grace_time of this V0040QosLimits.  # noqa: E501

        GraceTime  # noqa: E501

        :return: The grace_time of this V0040QosLimits.  # noqa: E501
        :rtype: int
        """
        return self._grace_time

    @grace_time.setter
    def grace_time(self, grace_time):
        """Sets the grace_time of this V0040QosLimits.

        GraceTime  # noqa: E501

        :param grace_time: The grace_time of this V0040QosLimits.  # noqa: E501
        :type: int
        """

        self._grace_time = grace_time

    @property
    def max(self):
        """Gets the max of this V0040QosLimits.  # noqa: E501


        :return: The max of this V0040QosLimits.  # noqa: E501
        :rtype: V0040QosLimitsMax
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this V0040QosLimits.


        :param max: The max of this V0040QosLimits.  # noqa: E501
        :type: V0040QosLimitsMax
        """

        self._max = max

    @property
    def factor(self):
        """Gets the factor of this V0040QosLimits.  # noqa: E501


        :return: The factor of this V0040QosLimits.  # noqa: E501
        :rtype: V0040Float64NoVal
        """
        return self._factor

    @factor.setter
    def factor(self, factor):
        """Sets the factor of this V0040QosLimits.


        :param factor: The factor of this V0040QosLimits.  # noqa: E501
        :type: V0040Float64NoVal
        """

        self._factor = factor

    @property
    def min(self):
        """Gets the min of this V0040QosLimits.  # noqa: E501


        :return: The min of this V0040QosLimits.  # noqa: E501
        :rtype: V0040QosLimitsMin
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this V0040QosLimits.


        :param min: The min of this V0040QosLimits.  # noqa: E501
        :type: V0040QosLimitsMin
        """

        self._min = min

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040QosLimits):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040QosLimits):
            return True

        return self.to_dict() != other.to_dict()
