# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040OpenapiMetaSlurm(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'version': 'V0040OpenapiMetaSlurmVersion',
        'release': 'str',
        'cluster': 'str'
    }

    attribute_map = {
        'version': 'version',
        'release': 'release',
        'cluster': 'cluster'
    }

    def __init__(self, version=None, release=None, cluster=None, local_vars_configuration=None):  # noqa: E501
        """V0040OpenapiMetaSlurm - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._version = None
        self._release = None
        self._cluster = None
        self.discriminator = None

        if version is not None:
            self.version = version
        if release is not None:
            self.release = release
        if cluster is not None:
            self.cluster = cluster

    @property
    def version(self):
        """Gets the version of this V0040OpenapiMetaSlurm.  # noqa: E501


        :return: The version of this V0040OpenapiMetaSlurm.  # noqa: E501
        :rtype: V0040OpenapiMetaSlurmVersion
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V0040OpenapiMetaSlurm.


        :param version: The version of this V0040OpenapiMetaSlurm.  # noqa: E501
        :type: V0040OpenapiMetaSlurmVersion
        """

        self._version = version

    @property
    def release(self):
        """Gets the release of this V0040OpenapiMetaSlurm.  # noqa: E501

        Slurm release string  # noqa: E501

        :return: The release of this V0040OpenapiMetaSlurm.  # noqa: E501
        :rtype: str
        """
        return self._release

    @release.setter
    def release(self, release):
        """Sets the release of this V0040OpenapiMetaSlurm.

        Slurm release string  # noqa: E501

        :param release: The release of this V0040OpenapiMetaSlurm.  # noqa: E501
        :type: str
        """

        self._release = release

    @property
    def cluster(self):
        """Gets the cluster of this V0040OpenapiMetaSlurm.  # noqa: E501

        Slurm cluster name  # noqa: E501

        :return: The cluster of this V0040OpenapiMetaSlurm.  # noqa: E501
        :rtype: str
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this V0040OpenapiMetaSlurm.

        Slurm cluster name  # noqa: E501

        :param cluster: The cluster of this V0040OpenapiMetaSlurm.  # noqa: E501
        :type: str
        """

        self._cluster = cluster

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040OpenapiMetaSlurm):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040OpenapiMetaSlurm):
            return True

        return self.to_dict() != other.to_dict()
