# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040QosLimitsMaxJobs(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'active_jobs': 'V0040QosLimitsMaxJobsActiveJobs',
        'per': 'V0040QosLimitsMaxJobsActiveJobsPer'
    }

    attribute_map = {
        'active_jobs': 'active_jobs',
        'per': 'per'
    }

    def __init__(self, active_jobs=None, per=None, local_vars_configuration=None):  # noqa: E501
        """V0040QosLimitsMaxJobs - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._active_jobs = None
        self._per = None
        self.discriminator = None

        if active_jobs is not None:
            self.active_jobs = active_jobs
        if per is not None:
            self.per = per

    @property
    def active_jobs(self):
        """Gets the active_jobs of this V0040QosLimitsMaxJobs.  # noqa: E501


        :return: The active_jobs of this V0040QosLimitsMaxJobs.  # noqa: E501
        :rtype: V0040QosLimitsMaxJobsActiveJobs
        """
        return self._active_jobs

    @active_jobs.setter
    def active_jobs(self, active_jobs):
        """Sets the active_jobs of this V0040QosLimitsMaxJobs.


        :param active_jobs: The active_jobs of this V0040QosLimitsMaxJobs.  # noqa: E501
        :type: V0040QosLimitsMaxJobsActiveJobs
        """

        self._active_jobs = active_jobs

    @property
    def per(self):
        """Gets the per of this V0040QosLimitsMaxJobs.  # noqa: E501


        :return: The per of this V0040QosLimitsMaxJobs.  # noqa: E501
        :rtype: V0040QosLimitsMaxJobsActiveJobsPer
        """
        return self._per

    @per.setter
    def per(self, per):
        """Sets the per of this V0040QosLimitsMaxJobs.


        :param per: The per of this V0040QosLimitsMaxJobs.  # noqa: E501
        :type: V0040QosLimitsMaxJobsActiveJobsPer
        """

        self._per = per

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040QosLimitsMaxJobs):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040QosLimitsMaxJobs):
            return True

        return self.to_dict() != other.to_dict()
