# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040PartitionInfoCpus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'task_binding': 'int',
        'total': 'int'
    }

    attribute_map = {
        'task_binding': 'task_binding',
        'total': 'total'
    }

    def __init__(self, task_binding=None, total=None, local_vars_configuration=None):  # noqa: E501
        """V0040PartitionInfoCpus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._task_binding = None
        self._total = None
        self.discriminator = None

        if task_binding is not None:
            self.task_binding = task_binding
        if total is not None:
            self.total = total

    @property
    def task_binding(self):
        """Gets the task_binding of this V0040PartitionInfoCpus.  # noqa: E501

        CpuBind  # noqa: E501

        :return: The task_binding of this V0040PartitionInfoCpus.  # noqa: E501
        :rtype: int
        """
        return self._task_binding

    @task_binding.setter
    def task_binding(self, task_binding):
        """Sets the task_binding of this V0040PartitionInfoCpus.

        CpuBind  # noqa: E501

        :param task_binding: The task_binding of this V0040PartitionInfoCpus.  # noqa: E501
        :type: int
        """

        self._task_binding = task_binding

    @property
    def total(self):
        """Gets the total of this V0040PartitionInfoCpus.  # noqa: E501

        TotalCPUs  # noqa: E501

        :return: The total of this V0040PartitionInfoCpus.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this V0040PartitionInfoCpus.

        TotalCPUs  # noqa: E501

        :param total: The total of this V0040PartitionInfoCpus.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040PartitionInfoCpus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040PartitionInfoCpus):
            return True

        return self.to_dict() != other.to_dict()
