# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040JobHet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'job_id': 'int',
        'job_offset': 'V0040Uint32NoVal'
    }

    attribute_map = {
        'job_id': 'job_id',
        'job_offset': 'job_offset'
    }

    def __init__(self, job_id=None, job_offset=None, local_vars_configuration=None):  # noqa: E501
        """V0040JobHet - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._job_id = None
        self._job_offset = None
        self.discriminator = None

        if job_id is not None:
            self.job_id = job_id
        if job_offset is not None:
            self.job_offset = job_offset

    @property
    def job_id(self):
        """Gets the job_id of this V0040JobHet.  # noqa: E501

        Heterogeneous job ID, if applicable  # noqa: E501

        :return: The job_id of this V0040JobHet.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this V0040JobHet.

        Heterogeneous job ID, if applicable  # noqa: E501

        :param job_id: The job_id of this V0040JobHet.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def job_offset(self):
        """Gets the job_offset of this V0040JobHet.  # noqa: E501


        :return: The job_offset of this V0040JobHet.  # noqa: E501
        :rtype: V0040Uint32NoVal
        """
        return self._job_offset

    @job_offset.setter
    def job_offset(self, job_offset):
        """Sets the job_offset of this V0040JobHet.


        :param job_offset: The job_offset of this V0040JobHet.  # noqa: E501
        :type: V0040Uint32NoVal
        """

        self._job_offset = job_offset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040JobHet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040JobHet):
            return True

        return self.to_dict() != other.to_dict()
