# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040InstanceTime(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'time_end': 'int',
        'time_start': 'int'
    }

    attribute_map = {
        'time_end': 'time_end',
        'time_start': 'time_start'
    }

    def __init__(self, time_end=None, time_start=None, local_vars_configuration=None):  # noqa: E501
        """V0040InstanceTime - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._time_end = None
        self._time_start = None
        self.discriminator = None

        if time_end is not None:
            self.time_end = time_end
        if time_start is not None:
            self.time_start = time_start

    @property
    def time_end(self):
        """Gets the time_end of this V0040InstanceTime.  # noqa: E501

        When the instance will end (UNIX timestamp)  # noqa: E501

        :return: The time_end of this V0040InstanceTime.  # noqa: E501
        :rtype: int
        """
        return self._time_end

    @time_end.setter
    def time_end(self, time_end):
        """Sets the time_end of this V0040InstanceTime.

        When the instance will end (UNIX timestamp)  # noqa: E501

        :param time_end: The time_end of this V0040InstanceTime.  # noqa: E501
        :type: int
        """

        self._time_end = time_end

    @property
    def time_start(self):
        """Gets the time_start of this V0040InstanceTime.  # noqa: E501

        When the instance will start (UNIX timestamp)  # noqa: E501

        :return: The time_start of this V0040InstanceTime.  # noqa: E501
        :rtype: int
        """
        return self._time_start

    @time_start.setter
    def time_start(self, time_start):
        """Sets the time_start of this V0040InstanceTime.

        When the instance will start (UNIX timestamp)  # noqa: E501

        :param time_start: The time_start of this V0040InstanceTime.  # noqa: E501
        :type: int
        """

        self._time_start = time_start

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040InstanceTime):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040InstanceTime):
            return True

        return self.to_dict() != other.to_dict()
