# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040OpenapiLicensesResp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'licenses': 'list[V0040License]',
        'last_update': 'V0040Uint64NoVal',
        'meta': 'V0040OpenapiMeta',
        'errors': 'list[V0040OpenapiError]',
        'warnings': 'list[V0040OpenapiWarning]'
    }

    attribute_map = {
        'licenses': 'licenses',
        'last_update': 'last_update',
        'meta': 'meta',
        'errors': 'errors',
        'warnings': 'warnings'
    }

    def __init__(self, licenses=None, last_update=None, meta=None, errors=None, warnings=None, local_vars_configuration=None):  # noqa: E501
        """V0040OpenapiLicensesResp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._licenses = None
        self._last_update = None
        self._meta = None
        self._errors = None
        self._warnings = None
        self.discriminator = None

        self.licenses = licenses
        self.last_update = last_update
        if meta is not None:
            self.meta = meta
        if errors is not None:
            self.errors = errors
        if warnings is not None:
            self.warnings = warnings

    @property
    def licenses(self):
        """Gets the licenses of this V0040OpenapiLicensesResp.  # noqa: E501


        :return: The licenses of this V0040OpenapiLicensesResp.  # noqa: E501
        :rtype: list[V0040License]
        """
        return self._licenses

    @licenses.setter
    def licenses(self, licenses):
        """Sets the licenses of this V0040OpenapiLicensesResp.


        :param licenses: The licenses of this V0040OpenapiLicensesResp.  # noqa: E501
        :type: list[V0040License]
        """
        if self.local_vars_configuration.client_side_validation and licenses is None:  # noqa: E501
            raise ValueError("Invalid value for `licenses`, must not be `None`")  # noqa: E501

        self._licenses = licenses

    @property
    def last_update(self):
        """Gets the last_update of this V0040OpenapiLicensesResp.  # noqa: E501


        :return: The last_update of this V0040OpenapiLicensesResp.  # noqa: E501
        :rtype: V0040Uint64NoVal
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this V0040OpenapiLicensesResp.


        :param last_update: The last_update of this V0040OpenapiLicensesResp.  # noqa: E501
        :type: V0040Uint64NoVal
        """
        if self.local_vars_configuration.client_side_validation and last_update is None:  # noqa: E501
            raise ValueError("Invalid value for `last_update`, must not be `None`")  # noqa: E501

        self._last_update = last_update

    @property
    def meta(self):
        """Gets the meta of this V0040OpenapiLicensesResp.  # noqa: E501


        :return: The meta of this V0040OpenapiLicensesResp.  # noqa: E501
        :rtype: V0040OpenapiMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this V0040OpenapiLicensesResp.


        :param meta: The meta of this V0040OpenapiLicensesResp.  # noqa: E501
        :type: V0040OpenapiMeta
        """

        self._meta = meta

    @property
    def errors(self):
        """Gets the errors of this V0040OpenapiLicensesResp.  # noqa: E501


        :return: The errors of this V0040OpenapiLicensesResp.  # noqa: E501
        :rtype: list[V0040OpenapiError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this V0040OpenapiLicensesResp.


        :param errors: The errors of this V0040OpenapiLicensesResp.  # noqa: E501
        :type: list[V0040OpenapiError]
        """

        self._errors = errors

    @property
    def warnings(self):
        """Gets the warnings of this V0040OpenapiLicensesResp.  # noqa: E501


        :return: The warnings of this V0040OpenapiLicensesResp.  # noqa: E501
        :rtype: list[V0040OpenapiWarning]
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this V0040OpenapiLicensesResp.


        :param warnings: The warnings of this V0040OpenapiLicensesResp.  # noqa: E501
        :type: list[V0040OpenapiWarning]
        """

        self._warnings = warnings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040OpenapiLicensesResp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040OpenapiLicensesResp):
            return True

        return self.to_dict() != other.to_dict()
