# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040StepNodes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'count': 'int',
        'range': 'str',
        'list': 'list[str]'
    }

    attribute_map = {
        'count': 'count',
        'range': 'range',
        'list': 'list'
    }

    def __init__(self, count=None, range=None, list=None, local_vars_configuration=None):  # noqa: E501
        """V0040StepNodes - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._count = None
        self._range = None
        self._list = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if range is not None:
            self.range = range
        if list is not None:
            self.list = list

    @property
    def count(self):
        """Gets the count of this V0040StepNodes.  # noqa: E501

        Number of nodes in the job step  # noqa: E501

        :return: The count of this V0040StepNodes.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this V0040StepNodes.

        Number of nodes in the job step  # noqa: E501

        :param count: The count of this V0040StepNodes.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def range(self):
        """Gets the range of this V0040StepNodes.  # noqa: E501

        Node(s) allocated to the job step  # noqa: E501

        :return: The range of this V0040StepNodes.  # noqa: E501
        :rtype: str
        """
        return self._range

    @range.setter
    def range(self, range):
        """Sets the range of this V0040StepNodes.

        Node(s) allocated to the job step  # noqa: E501

        :param range: The range of this V0040StepNodes.  # noqa: E501
        :type: str
        """

        self._range = range

    @property
    def list(self):
        """Gets the list of this V0040StepNodes.  # noqa: E501


        :return: The list of this V0040StepNodes.  # noqa: E501
        :rtype: list[str]
        """
        return self._list

    @list.setter
    def list(self, list):
        """Sets the list of this V0040StepNodes.


        :param list: The list of this V0040StepNodes.  # noqa: E501
        :type: list[str]
        """

        self._list = list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040StepNodes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040StepNodes):
            return True

        return self.to_dict() != other.to_dict()
