# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm  # noqa: E501

    The version of the OpenAPI document: Slurm-24.05.4&openapi/slurmctld&openapi/slurmdbd
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V0040QosLimitsMaxWallClockPer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'qos': 'V0040Uint32NoVal',
        'job': 'V0040Uint32NoVal'
    }

    attribute_map = {
        'qos': 'qos',
        'job': 'job'
    }

    def __init__(self, qos=None, job=None, local_vars_configuration=None):  # noqa: E501
        """V0040QosLimitsMaxWallClockPer - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._qos = None
        self._job = None
        self.discriminator = None

        if qos is not None:
            self.qos = qos
        if job is not None:
            self.job = job

    @property
    def qos(self):
        """Gets the qos of this V0040QosLimitsMaxWallClockPer.  # noqa: E501


        :return: The qos of this V0040QosLimitsMaxWallClockPer.  # noqa: E501
        :rtype: V0040Uint32NoVal
        """
        return self._qos

    @qos.setter
    def qos(self, qos):
        """Sets the qos of this V0040QosLimitsMaxWallClockPer.


        :param qos: The qos of this V0040QosLimitsMaxWallClockPer.  # noqa: E501
        :type: V0040Uint32NoVal
        """

        self._qos = qos

    @property
    def job(self):
        """Gets the job of this V0040QosLimitsMaxWallClockPer.  # noqa: E501


        :return: The job of this V0040QosLimitsMaxWallClockPer.  # noqa: E501
        :rtype: V0040Uint32NoVal
        """
        return self._job

    @job.setter
    def job(self, job):
        """Sets the job of this V0040QosLimitsMaxWallClockPer.


        :param job: The job of this V0040QosLimitsMaxWallClockPer.  # noqa: E501
        :type: V0040Uint32NoVal
        """

        self._job = job

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V0040QosLimitsMaxWallClockPer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V0040QosLimitsMaxWallClockPer):
            return True

        return self.to_dict() != other.to_dict()
